package me.chester.minitruco.core;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class JogadorDiffblueTest {
    /**
     * Method under test: {@link Jogador#sanitizaNome(String)}
     */
    @Test
    void testSanitizaNome() {
        // Arrange, Act and Assert
        assertEquals("Nome", Jogador.sanitizaNome("Nome"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("^bot$"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("025", Jogador.sanitizaNome("^(.{0,25}).*$"));
        assertEquals("1", Jogador.sanitizaNome("$1"));
        assertEquals("sem_nome", Jogador.sanitizaNome("sem_nome_"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("bot;"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("bot_"));
        assertEquals("botbot", Jogador.sanitizaNome("bot^bot$"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("bot[-_ \r\n]"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("bot_$"));
        assertEquals("bota_zA_Z0_9À_ÿ", Jogador.sanitizaNome("bot[^a-zA-Z0-9À-ÿ ]"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("bot +"));
        assertEquals("bot025", Jogador.sanitizaNome("bot^(.{0,25}).*$"));
        assertEquals("bot1", Jogador.sanitizaNome("bot$1"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("bot^[-_ ]*$"));
        assertEquals("botsem_nome", Jogador.sanitizaNome("botsem_nome_"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome(" [^a-zA-Z0-9À-ÿ ]"));
        assertEquals("sem_nome", Jogador.sanitizaNome(" sem_nome_"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome(";bot"));
        assertEquals("UUU", Jogador.sanitizaNome(";UUU"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome(";^bot$"));
        assertEquals("Nome", Jogador.sanitizaNome(";Nome"));
        assertEquals("42", Jogador.sanitizaNome(";42"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome(";[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("unnamed", Jogador.sanitizaNome(";unnamed"));
        assertEquals("025", Jogador.sanitizaNome(";^(.{0,25}).*$"));
        assertEquals("1", Jogador.sanitizaNome(";$1"));
        assertEquals("sem_nome", Jogador.sanitizaNome(";sem_nome_"));
        assertEquals("UUU", Jogador.sanitizaNome("UUU;"));
        assertEquals("UUU", Jogador.sanitizaNome("UUU_"));
        assertEquals("UUUbot", Jogador.sanitizaNome("UUU^bot$"));
        assertEquals("UUU", Jogador.sanitizaNome("UUU[-_ \r\n]"));
        assertEquals("UUU", Jogador.sanitizaNome("UUU_$"));
        assertEquals("UUUa_zA_Z0_9À_ÿ", Jogador.sanitizaNome("UUU[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("UUU", Jogador.sanitizaNome("UUU +"));
        assertEquals("UUU025", Jogador.sanitizaNome("UUU^(.{0,25}).*$"));
        assertEquals("UUU1", Jogador.sanitizaNome("UUU$1"));
        assertEquals("UUU", Jogador.sanitizaNome("UUU^[-_ ]*$"));
        assertEquals("UUUsem_nome", Jogador.sanitizaNome("UUUsem_nome_"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("_bot"));
        assertEquals("UUU", Jogador.sanitizaNome("_UUU"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("_^bot$"));
        assertEquals("Nome", Jogador.sanitizaNome("_Nome"));
        assertEquals("42", Jogador.sanitizaNome("_42"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("_[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("unnamed", Jogador.sanitizaNome("_unnamed"));
        assertEquals("025", Jogador.sanitizaNome("_^(.{0,25}).*$"));
        assertEquals("1", Jogador.sanitizaNome("_$1"));
        assertEquals("sem_nome", Jogador.sanitizaNome("_sem_nome_"));
        assertEquals("botbot", Jogador.sanitizaNome("^bot$bot"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("^bot$;"));
        assertEquals("Nome", Jogador.sanitizaNome("Nome;"));
        assertEquals("botUUU", Jogador.sanitizaNome("^bot$UUU"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("^bot$_"));
        assertEquals("Nome", Jogador.sanitizaNome("Nome_"));
        assertEquals("botbot", Jogador.sanitizaNome("^bot$^bot$"));
        assertEquals("botNome", Jogador.sanitizaNome("^bot$Nome"));
        assertEquals("Nomebot", Jogador.sanitizaNome("Nome^bot$"));
        assertEquals("bot42", Jogador.sanitizaNome("^bot$42"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("^bot$[-_ \r\n]"));
        assertEquals("Nome", Jogador.sanitizaNome("Nome[-_ \r\n]"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("^bot$_$"));
        assertEquals("Nome", Jogador.sanitizaNome("Nome_$"));
        assertEquals("bota_zA_Z0_9À_ÿ", Jogador.sanitizaNome("^bot$[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("Nomea_zA_Z0_9À_ÿ", Jogador.sanitizaNome("Nome[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("botunnamed", Jogador.sanitizaNome("^bot$unnamed"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("^bot$ +"));
        assertEquals("Nome", Jogador.sanitizaNome("Nome +"));
        assertEquals("bot025", Jogador.sanitizaNome("^bot$^(.{0,25}).*$"));
        assertEquals("Nome025", Jogador.sanitizaNome("Nome^(.{0,25}).*$"));
        assertEquals("bot1", Jogador.sanitizaNome("^bot$$1"));
        assertEquals("Nome1", Jogador.sanitizaNome("Nome$1"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("^bot$^[-_ ]*$"));
        assertEquals("Nome", Jogador.sanitizaNome("Nome^[-_ ]*$"));
        assertEquals("botsem_nome", Jogador.sanitizaNome("^bot$sem_nome_"));
        assertEquals("Nomesem_nome", Jogador.sanitizaNome("Nomesem_nome_"));
        assertEquals("42", Jogador.sanitizaNome("42;"));
        assertEquals("42", Jogador.sanitizaNome("42_"));
        assertEquals("42bot", Jogador.sanitizaNome("42^bot$"));
        assertEquals("42", Jogador.sanitizaNome("42[-_ \r\n]"));
        assertEquals("42", Jogador.sanitizaNome("42_$"));
        assertEquals("42a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("42[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("42", Jogador.sanitizaNome("42 +"));
        assertEquals("42025", Jogador.sanitizaNome("42^(.{0,25}).*$"));
        assertEquals("421", Jogador.sanitizaNome("42$1"));
        assertEquals("42", Jogador.sanitizaNome("42^[-_ ]*$"));
        assertEquals("42sem_nome", Jogador.sanitizaNome("42sem_nome_"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("[-_ \r\n]bot"));
        assertEquals("UUU", Jogador.sanitizaNome("[-_ \r\n]UUU"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("[-_ \r\n]^bot$"));
        assertEquals("Nome", Jogador.sanitizaNome("[-_ \r\n]Nome"));
        assertEquals("42", Jogador.sanitizaNome("[-_ \r\n]42"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("[-_ \r\n][^a-zA-Z0-9À-ÿ ]"));
        assertEquals("unnamed", Jogador.sanitizaNome("[-_ \r\n]unnamed"));
        assertEquals("025", Jogador.sanitizaNome("[-_ \r\n]^(.{0,25}).*$"));
        assertEquals("1", Jogador.sanitizaNome("[-_ \r\n]$1"));
        assertEquals("sem_nome", Jogador.sanitizaNome("[-_ \r\n]sem_nome_"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("_$bot"));
        assertEquals("UUU", Jogador.sanitizaNome("_$UUU"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("_$^bot$"));
        assertEquals("Nome", Jogador.sanitizaNome("_$Nome"));
        assertEquals("42", Jogador.sanitizaNome("_$42"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("_$[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("unnamed", Jogador.sanitizaNome("_$unnamed"));
        assertEquals("025", Jogador.sanitizaNome("_$^(.{0,25}).*$"));
        assertEquals("1", Jogador.sanitizaNome("_$$1"));
        assertEquals("sem_nome", Jogador.sanitizaNome("_$sem_nome_"));
        assertEquals("a_zA_Z0_9À_ÿ_bot", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]bot"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ] "));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ];"));
        assertEquals("a_zA_Z0_9À_ÿ_UUU", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]UUU"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]_"));
        assertEquals("a_zA_Z0_9À_ÿ_bot", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]^bot$"));
        assertEquals("a_zA_Z0_9À_ÿ_Nome", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]Nome"));
        assertEquals("a_zA_Z0_9À_ÿ_42", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]42"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ][-_ \r\n]"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]_$"));
        assertEquals("a_zA_Z0_9À_ÿ_a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ][^a-zA-Z0-9À-ÿ ]"));
        assertEquals("a_zA_Z0_9À_ÿ_unnamed", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]unnamed"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ] +"));
        assertEquals("a_zA_Z0_9À_ÿ_025", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]^(.{0,25}).*$"));
        assertEquals("a_zA_Z0_9À_ÿ_1", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]$1"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]^[-_ ]*$"));
        assertEquals("a_zA_Z0_9À_ÿ_sem_nome", Jogador.sanitizaNome("[^a-zA-Z0-9À-ÿ ]sem_nome_"));
        assertEquals("unnamed", Jogador.sanitizaNome("unnamed;"));
        assertEquals("unnamed", Jogador.sanitizaNome("unnamed_"));
        assertEquals("unnamedbot", Jogador.sanitizaNome("unnamed^bot$"));
        assertEquals("unnamed", Jogador.sanitizaNome("unnamed[-_ \r\n]"));
        assertEquals("unnamed", Jogador.sanitizaNome("unnamed_$"));
        assertEquals("unnameda_zA_Z0_9À_ÿ", Jogador.sanitizaNome("unnamed[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("unnamed", Jogador.sanitizaNome("unnamed +"));
        assertEquals("unnamed025", Jogador.sanitizaNome("unnamed^(.{0,25}).*$"));
        assertEquals("unnamed1", Jogador.sanitizaNome("unnamed$1"));
        assertEquals("unnamed", Jogador.sanitizaNome("unnamed^[-_ ]*$"));
        assertEquals("unnamedsem_nome", Jogador.sanitizaNome("unnamedsem_nome_"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome(" +bot"));
        assertEquals("UUU", Jogador.sanitizaNome(" +UUU"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome(" +^bot$"));
        assertEquals("Nome", Jogador.sanitizaNome(" +Nome"));
        assertEquals("42", Jogador.sanitizaNome(" +42"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome(" +[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("unnamed", Jogador.sanitizaNome(" +unnamed"));
        assertEquals("025", Jogador.sanitizaNome(" +^(.{0,25}).*$"));
        assertEquals("1", Jogador.sanitizaNome(" +$1"));
        assertEquals("sem_nome", Jogador.sanitizaNome(" +sem_nome_"));
        assertEquals("025bot", Jogador.sanitizaNome("^(.{0,25}).*$bot"));
        assertEquals("025", Jogador.sanitizaNome("^(.{0,25}).*$;"));
        assertEquals("025UUU", Jogador.sanitizaNome("^(.{0,25}).*$UUU"));
        assertEquals("025", Jogador.sanitizaNome("^(.{0,25}).*$_"));
        assertEquals("025bot", Jogador.sanitizaNome("^(.{0,25}).*$^bot$"));
        assertEquals("025Nome", Jogador.sanitizaNome("^(.{0,25}).*$Nome"));
        assertEquals("02542", Jogador.sanitizaNome("^(.{0,25}).*$42"));
        assertEquals("025", Jogador.sanitizaNome("^(.{0,25}).*$[-_ \r\n]"));
        assertEquals("025", Jogador.sanitizaNome("^(.{0,25}).*$_$"));
        assertEquals("025a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("^(.{0,25}).*$[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("025unnamed", Jogador.sanitizaNome("^(.{0,25}).*$unnamed"));
        assertEquals("025", Jogador.sanitizaNome("^(.{0,25}).*$ +"));
        assertEquals("025025", Jogador.sanitizaNome("^(.{0,25}).*$^(.{0,25}).*$"));
        assertEquals("0251", Jogador.sanitizaNome("^(.{0,25}).*$$1"));
        assertEquals("025", Jogador.sanitizaNome("^(.{0,25}).*$^[-_ ]*$"));
        assertEquals("025sem_nome", Jogador.sanitizaNome("^(.{0,25}).*$sem_nome_"));
        assertEquals("1bot", Jogador.sanitizaNome("$1bot"));
        assertEquals("1", Jogador.sanitizaNome("$1;"));
        assertEquals("1UUU", Jogador.sanitizaNome("$1UUU"));
        assertEquals("1", Jogador.sanitizaNome("$1_"));
        assertEquals("1bot", Jogador.sanitizaNome("$1^bot$"));
        assertEquals("1Nome", Jogador.sanitizaNome("$1Nome"));
        assertEquals("142", Jogador.sanitizaNome("$142"));
        assertEquals("1", Jogador.sanitizaNome("$1[-_ \r\n]"));
        assertEquals("1", Jogador.sanitizaNome("$1_$"));
        assertEquals("1a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("$1[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("1unnamed", Jogador.sanitizaNome("$1unnamed"));
        assertEquals("1", Jogador.sanitizaNome("$1 +"));
        assertEquals("1025", Jogador.sanitizaNome("$1^(.{0,25}).*$"));
        assertEquals("11", Jogador.sanitizaNome("$1$1"));
        assertEquals("1", Jogador.sanitizaNome("$1^[-_ ]*$"));
        assertEquals("1sem_nome", Jogador.sanitizaNome("$1sem_nome_"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("^[-_ ]*$bot"));
        assertEquals("UUU", Jogador.sanitizaNome("^[-_ ]*$UUU"));
        assertEquals(JogadorBot.APELIDO_BOT, Jogador.sanitizaNome("^[-_ ]*$^bot$"));
        assertEquals("Nome", Jogador.sanitizaNome("^[-_ ]*$Nome"));
        assertEquals("42", Jogador.sanitizaNome("^[-_ ]*$42"));
        assertEquals("a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("^[-_ ]*$[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("unnamed", Jogador.sanitizaNome("^[-_ ]*$unnamed"));
        assertEquals("025", Jogador.sanitizaNome("^[-_ ]*$^(.{0,25}).*$"));
        assertEquals("1", Jogador.sanitizaNome("^[-_ ]*$$1"));
        assertEquals("sem_nome", Jogador.sanitizaNome("^[-_ ]*$sem_nome_"));
        assertEquals("sem_nome_bot", Jogador.sanitizaNome("sem_nome_bot"));
        assertEquals("sem_nome", Jogador.sanitizaNome("sem_nome_ "));
        assertEquals("sem_nome", Jogador.sanitizaNome("sem_nome_;"));
        assertEquals("sem_nome_UUU", Jogador.sanitizaNome("sem_nome_UUU"));
        assertEquals("sem_nome", Jogador.sanitizaNome("sem_nome__"));
        assertEquals("sem_nome_bot", Jogador.sanitizaNome("sem_nome_^bot$"));
        assertEquals("sem_nome_Nome", Jogador.sanitizaNome("sem_nome_Nome"));
        assertEquals("sem_nome_42", Jogador.sanitizaNome("sem_nome_42"));
        assertEquals("sem_nome", Jogador.sanitizaNome("sem_nome_[-_ \r\n]"));
        assertEquals("sem_nome", Jogador.sanitizaNome("sem_nome__$"));
        assertEquals("sem_nome_a_zA_Z0_9À_ÿ", Jogador.sanitizaNome("sem_nome_[^a-zA-Z0-9À-ÿ ]"));
        assertEquals("sem_nome_unnamed", Jogador.sanitizaNome("sem_nome_unnamed"));
        assertEquals("sem_nome", Jogador.sanitizaNome("sem_nome_ +"));
        assertEquals("sem_nome_025", Jogador.sanitizaNome("sem_nome_^(.{0,25}).*$"));
        assertEquals("sem_nome_1", Jogador.sanitizaNome("sem_nome_$1"));
        assertEquals("sem_nome", Jogador.sanitizaNome("sem_nome_^[-_ ]*$"));
        assertEquals("sem_nome_sem_nome", Jogador.sanitizaNome("sem_nome_sem_nome_"));
        assertEquals("botbot", Jogador.sanitizaNome("botbot;"));
        assertEquals("botbot", Jogador.sanitizaNome("botbot_"));
        assertEquals("botbotbot", Jogador.sanitizaNome("botbot^bot$"));
        assertEquals("botbot", Jogador.sanitizaNome("botbot[-_ \r\n]"));
        assertEquals("botbot", Jogador.sanitizaNome("botbot_$"));
        assertEquals("botbota_zA_Z0_9À_ÿ", Jogador.sanitizaNome("botbot[^a-zA-Z0-9À-ÿ ]"));
    }
}
